config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users,
             ActiveAdmin::Devise.config.merge({ class_name: 'AdminUser',
                                                controllers: { sessions: 'custom_active_admin_sessions' } })

  ActiveAdmin.routes(self)
  devise_for :users, skip: :registrations
  get '/pages/index', to: 'pages#index'
  resources :parts
  resources :cart_items, only: [:create]
  resources :carts do
    resources :cart_items, only: %i[create update destroy]
    member do
      delete 'clear_cart'
    end
  end

  get 'orders/lager_order', to: 'orders#lager_order', as: 'lager_order'
  post 'orders/create_lager_order', to: 'orders#create_lager_order', as: 'create_lager_order'

  resources :orders, only: %i[new create show update edit] do
    member do
      get :complete
      get :set_to_pending
      get :set_to_missing_parts
      post :add_part
      delete :delete_part
      get :set_to_hide
      get :set_to_visible
    end
  end

  root 'pages#welcome'

  get '/get_full_address', to: 'orders#get_full_address'

  namespace :warehouse do
    resources :storages, only: %i[index show update] do
      member do
        # ... (inne akcje member)
        get :print
      end

      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get 'parts_on_site'
        get :hidden_orders
        get :visible_orders
        get :print
      end
    end
  end

  namespace :tracking do
    resources :orders do
      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get :your_orders
      end
    end
  end
end

app/controllers/warehouse/storages_controller.rb
# frozen_string_literal: true

module Warehouse
  class StoragesController < ApplicationController
    layout 'warehouse'

    def index
      @all_orders_view = false
      start_date = params[:start_date].presence
      end_date = params[:end_date].presence
      site_id = params[:site].presence
      @start_date = params[:start_date]
      @end_date = params[:end_date]

      @orders = filtered_orders(recent_orders.order(created_at: :desc))

      if start_date && end_date
        start_date = start_date.to_date.beginning_of_day
        end_date = end_date.to_date.end_of_day
        @orders = filtered_orders(@orders.where(created_at: start_date..end_date))
        @all_orders_view = true
        flash[:notice] = 'Date selected'
      end

      if site_id
        site = Site.find(site_id)
        @orders = filtered_orders(@orders.where(building_site: site.name))
        @site_name = site.name
      end
      @orders = @orders.limit(100) unless @all_orders_view
    end

    def show
      @order = Order.find(params[:id])

      if params[:system].present? && !params[:system].empty?
        system = System.find_by('LOWER(name) = ?', params[:system].downcase)
        @categories = system ? system.categories : Category.none
      else
        @categories = Category.none
      end

      if params[:category].present? && params[:category] != 'Select category'
        category = Category.find_by('LOWER(name) = ?', params[:category].downcase)
        @parts = category ? category.parts.order(description: :asc) : Part.none
      else
        @parts = Part.none
      end
    end

    def update
      @order = Order.find(params[:id])
      if @order.update(order_params)
        @order.in_progress!
        if params[:order][:send_email] == '1'
          OrderMailer.storage_confirmation(@order, current_user).deliver_now
          flash[:notice] = 'Emails sent. Remember to accept order as completed'

        else
          flash[:notice] = 'Remember to accept order as completed'
        end
        redirect_to warehouse_storages_path

      else
        render :show, alert: 'Something goes wrong'
      end
    end

    def parts_on_site
      return unless params[:site_id]

      @site = Site.find(params[:site_id])
      @parts = {}

      orders = Order.where(building_site: @site.name).where(status: %w[completed missing_parts])
      orders.each do |order|
        order.order_lists.each do |order_list|
          part = order_list.part
          ordered_quantity = order_list.quantity
          delivered_quantity = order_list.delivery_quantity || 0
          @parts[part] ||= { ordered: 0, delivered: 0 }
          @parts[part][:ordered] += ordered_quantity
          @parts[part][:delivered] += delivered_quantity
        end
      end
    end

    def search_orders
      site_id = params[:site].presence
      if site_id
        site = Site.find(site_id)
        @orders = filtered_orders(Order.where(building_site: site.name))
        @site_name = site.name # Assigning the site name
      end
      render :index
    end

    def all_orders
      @orders = filtered_orders(Order.order(created_at: :desc))
      @all_orders_view = true
      render :index
    end

    def completed_orders
      @orders = filtered_orders(Order.where(status: 'completed').order(created_at: :desc).limit(100))
      @status = 'completed'
      render :index
    end

    def pending_orders
      @orders = filtered_orders(Order.where(status: 'pending').order(created_at: :desc).limit(100))
      @status = 'pending'
      render :index
    end

    def in_progress_orders
      @orders = filtered_orders(Order.where(status: 'in_progress').order(created_at: :desc).limit(100))
      @status = 'in progress'
      render :index
    end

    def missing_parts_orders
      @orders = filtered_orders(Order.where(status: 'missing_parts').order(created_at: :desc).limit(100))
      @status = 'missing parts'
      render :index
    end

    def hidden_orders
      @orders = Order.where(hidden: true).order(created_at: :desc)
      render :index
    end

    def print
      @order = Order.find(params[:id])
      render pdf: "order_#{@order.id}", template: 'warehouse/storages/print',
             margin: { top: 10, bottom: 10, left: 15, right: 15 }
    end

    private

    def filtered_orders(base_query)
      if params[:show_hidden] == 'true'
        base_query
      else
        base_query.where(hidden: false)
      end
    end

    def recent_orders
      two_months_ago = 2.months.ago
      Order.where('created_at > ?', two_months_ago)
    end

    def order_params
      params.require(:order).permit(:new_delivery_date, :car_number, :storage_info, :hidden, :send_email,
                                    order_lists_attributes: %i[id delivery_quantity checkbox])
    end
  end
end

app/views/warehouse/storages/index.html.erb
<button id="toggle-storage-menu" class="ml-4 btn btn-primary  rounded-lg p-1 flex inline bg-neutral-200 hover:bg-neutral-300" onclick="toggleMenu()"><%= image_tag "menu.png", class: "w-6 h-6 flex inline mr-1 " %>  Storage Menu</button>
<div id="storage-menu" class="transition-all duration-500 max-h-0 overflow-hidden mt-2">
   <div class="mb-2">
  <%= form_with url: warehouse_storages_path, method: :get, local: true do |form| %>
    <%= form.label :site, "Search for:", class: "mr-1" %> 
    <%= form.collection_select :site, Site.order(:name), :id, :name, { prompt: "Choose a site" }, { class: "w-44 rounded-lg p-2" } %>
    
    <%= form.label :start_date, "From:" %>
    <%= form.date_field :start_date, class: "w-20 rounded-lg" %>
    <%= form.label :end_date, "To:" %>
    <%= form.date_field :end_date, class: "w-20 rounded-lg" %>
    
    <%= image_submit_tag 'search.png', class: 'w-8 h-8', alt: 'Search' %>
  <% end %>
</div>

  <div class="flex justify-between ">
    <div class="flex inline ">
      Select only:
        <%= button_to pending_orders_warehouse_storages_path, method: :get, class: 'your-button-classes m-2' do %>
        <%= image_tag('hourglass.png', size: '30x30', alt: 'Show Completed Orders') %>
      <% end %>
        <%= button_to in_progress_orders_warehouse_storages_path, method: :get, class: 'your-button-classes m-2' do %>
        <%= image_tag('list.png', size: '30x30', alt: 'Show Completed Orders') %>
      <% end %>
       <%= button_to missing_parts_orders_warehouse_storages_path, method: :get, class: 'your-button-classes m-2' do %>
        <%= image_tag('missing_parts.png', size: '30x30', alt: 'Show Missing Orders') %>
      <% end %>
      <%= button_to completed_orders_warehouse_storages_path, method: :get, class: 'your-button-classes m-2' do %>
        <%= image_tag('ok.png', size: '30x30', alt: 'Show Completed Orders') %>
      <% end %>
     <%= button_to hidden_orders_warehouse_storages_path, method: :get, class: 'your-button-classes m-2' do %>
        <%= image_tag('hide.png', class: "", size: '30x30', alt: 'Show Hidden Orders') %>
      <% end %>
    </div>

    <div class= "flex inline justify-end">
      <div data-controller="lightbox">
        <%= link_to asset_path('instruction.png'), data: { lightbox: 'instruction', title: 'Instruction' } do %>
          <div class= "flex inline">
          <%= image_tag('instruction_img.png', size: '20x20', class: 'inline mr-1') %>
          <%= button_to " Instruction", class: "your-button-classes ml-2" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <p class="border-b-2"><%= button_to 'Show All Orders', all_orders_warehouse_storages_path, method: :get, class: 'your-button-classes' %></p>

</div>
  


<% if @start_date && @end_date %>
  <p class="flex justify-center text-slate-400 mt-2">Orders from <%= @start_date %> to <%= @end_date %></p>
<% end %>
<% if @site_name %>
  <p class="flex justify-center text-slate-400 mt-2">Orders for site: <%= @site_name %></p>
<% end %>


  <% if @orders.present?  %>
 <% if @all_orders_view == true %>
  <h1 class="text-center m-4">All orders</h1>
<% else %>
  <h1 class="text-center m-4">Last 100 orders in Two months:</h1>
<% end %>
<div class="flex justify-center items-center">

<table class="table-fixed min-w-[600px]">
  <thead>
    <tr>
      <th>Order no:</th>
      <th>Site</th>
      <th>Created</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr class="transition duration-300 hover:bg-slate-300 border ">
        <td class="m-2"> <%= link_to warehouse_storage_path(order), class: "ml-2" do %>
        <% if order.hidden == false%>
            <%= image_tag('go_to.png', size: '30x30', class: 'inline') %>
          <% else %>
            <%= image_tag('hide.png', size: '30x30', class: 'inline') %>
          <% end %>
          <%= order.id %>
        <% end %></td>
        <td class="m-2 text-sm "><%= order.building_site %></td>
        <td class="m-2 text-sm text-center"> <%= order.created_at.strftime("%Y-%m-%d") %>
  <br/>
  <%= order.created_at.strftime("%H:%M")  %></td>
        <td class="m-2 border-r-2">
          <% if order.status == "completed" %>
            <p class="text-green-400"><%= image_tag('ok.png', size: '40x40', alt: "Completed") %></p>
          <% elsif order.status == "pending" %>
            <p class="text-red-400"><%= image_tag('hourglass.png', size: '40x40', alt: "Pending") %></p>
            <% elsif order.status == "missing_parts" %>
            <p class="text-text-amber-600"><%= image_tag('missing_parts.png', size: '40x40', alt: "Missing Parts") %></p>
          <% else %>
            <p class="text-blue-400"><%= image_tag('list.png', size: '40x40', alt: "In Progress") %></p>
          <% end %>
        </td>
        <td class="m-2"><td class="p-1"><div class="relative" data-te-dropdown-position="dropstart">
  <button
    class=" flex items-center whitespace-nowrap rounded bg-slate-400 pb-1 pl-1  pt-1 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] motion-reduce:transition-none dark:shadow-[0_4px_9px_-4px_rgba(59,113,202,0.5)] dark:hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)] dark:active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.2),0_4px_18px_0_rgba(59,113,202,0.1)]"
    type="button"
    id="dropdownMenuButton1s"
    data-te-dropdown-toggle-ref
    aria-expanded="false"
    data-te-ripple-init
    data-te-ripple-color="light">
    <span class="mr-2">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
        fill="currentColor"
        class="h-5 w-5">
        <path
          fill-rule="evenodd"
          d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
          clip-rule="evenodd" />
      </svg>
    </span>
    
  </button>
  <ul
    class="absolute z-[1000] float-left m-0 hidden min-w-max list-none overflow-hidden rounded-lg border-none bg-white bg-clip-padding text-left text-base shadow-lg dark:bg-neutral-700 [&[data-te-dropdown-show]]:block"
    aria-labelledby="dropdownMenuButton1s"
    data-te-dropdown-menu-ref>
    <li>
      <%= link_to complete_order_path(order), method: :get, class: "block w-full whitespace-nowrap bg-transparent px-4 py-2 text-sm font-normal text-neutral-700 hover:bg-neutral-100 active:text-neutral-800 active:no-underline disabled:pointer-events-none disabled:bg-transparent disabled:text-neutral-400 dark:text-neutral-200 dark:hover:bg-neutral-600" do %>
    <%= image_tag('complete.png', class: "w-8 h-8 min-w-[15px] min-h-[15px] mr-1") %>
  <% end %>
      
    </li>
    <li>
    <%= link_to set_to_missing_parts_order_path(order), method: :get, class: "block w-full whitespace-nowrap bg-transparent px-4 py-2 text-sm font-normal text-neutral-700 hover:bg-neutral-100 active:text-neutral-800 active:no-underline disabled:pointer-events-none disabled:bg-transparent disabled:text-neutral-400 dark:text-neutral-200 dark:hover:bg-neutral-600" do %>
    <%= image_tag('missing_parts.png', class: "w-8 h-8 min-w-[15px] min-h-[15px] mr-1") %>
  <% end %>
    </li>
    <li>
    <%= link_to set_to_pending_order_path(order), method: :get, class: "block w-full whitespace-nowrap bg-transparent px-4 py-2 text-sm font-normal text-neutral-700 hover:bg-neutral-100 active:text-neutral-800 active:no-underline disabled:pointer-events-none disabled:bg-transparent disabled:text-neutral-400 dark:text-neutral-200 dark:hover:bg-neutral-600" do %>
    <%= image_tag('hourglass.png', class: "w-8 h-8 min-w-[15px] min-h-[15px] mr-1") %>
  <% end %>
    </li>
<li>
   <% if order.hidden == false %>
    <%= link_to set_to_hide_order_path(order), method: :get, class: "block w-full whitespace-nowrap bg-transparent px-4 py-2 text-sm font-normal text-neutral-700 hover:bg-neutral-100 active:text-neutral-800 active:no-underline disabled:pointer-events-none disabled:bg-transparent disabled:text-neutral-400 dark:text-neutral-200 dark:hover:bg-neutral-600" do %>
    <%= image_tag('hide.png', class: "w-8 h-8 min-w-[15px] min-h-[15px] mr-1") %>
  <% end %>
    <% else %>
    <%= link_to set_to_visible_order_path(order), method: :get, class: "block w-full whitespace-nowrap bg-transparent px-4 py-2 text-sm font-normal text-neutral-700 hover:bg-neutral-100 active:text-neutral-800 active:no-underline disabled:pointer-events-none disabled:bg-transparent disabled:text-neutral-400 dark:text-neutral-200 dark:hover:bg-neutral-600" do %>
    <%= image_tag('visible.png', class: "w-8 h-8 min-w-[15px] min-h-[15px] mr-1") %>
    <% end %>
    <% end %>
    </li>
  </ul>
</div>
        </td></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>

<p class="flex justify-center item-center mt-10" >No orders <%= @status %></p>
<%end%>



</div>
 


<script>
// Funkcja przełączająca menu
function toggleMenu() {
  var menu = document.getElementById('storage-menu');
  if (menu.style.maxHeight === "" || menu.style.maxHeight === "0px") {
    menu.style.maxHeight = menu.scrollHeight + "px"; // Ustaw maksymalną wysokość na rzeczywistą wysokość elementu
    localStorage.setItem('storageMenuState', 'open'); // Zapisz stan jako otwarty
  } else {
    menu.style.maxHeight = "0px"; // Zresetuj maksymalną wysokość, aby zwinąć menu
    localStorage.setItem('storageMenuState', 'closed'); // Zapisz stan jako zamknięty
  }
}

// Sprawdź stan przy ładowaniu strony
document.addEventListener('DOMContentLoaded', (event) => {
  var menu = document.getElementById('storage-menu');
  var state = localStorage.getItem('storageMenuState');
  if (state === 'open') {
    menu.style.maxHeight = menu.scrollHeight + "px"; // Ustaw maksymalną wysokość na rzeczywistą wysokość elementu, jeśli menu było wcześniej otwarte
  }
});
</script>

app/views/warehouse/storages/parts_on_site.html.erb
<%= form_with url: parts_on_site_warehouse_storages_path, method: :get do |f| %>
  <%= f.label :site_id, 'Wybierz budowę:' %>
  <%= f.collection_select :site_id, Site.all, :id, :name, include_blank: 'Wybierz budowę' %>
  <%= f.submit 'Wybierz' %>
<% end %>

<% if @site %>
  <h2>Parts on site <%= @site.name %></h2>

  <table>
    <thead>
      <tr>
        <th>Number</th>
        <th>Description</th>
        <th>Ordered/Delivered</th>
      </tr>
    </thead>
    <tbody>
      <% @parts.each do |part, quantities| %>
        <tr>
          <td><%= part.name %></td>
          <td><%= part.description %></td>
          <td><%= quantities[:ordered] %>/<%= quantities[:delivered] %> stk</td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/warehouse/storages/print.html.erb
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>

<h1>Order #<%= @order.id %> Site: <strong><%= @order.building_site %></strong></h1>
<h2>Site info: <%= @order.building_site_info %> </h2>



    <p>Scaffolder: <strong><%= @order.user.email %></strong></p>
    <p>Delivery Date: <strong><%= @order.delivery_date.strftime("%d-%m-%Y")  %></strong> /// New Delivery Date: <strong><%= @order.new_delivery_date.strftime("%d-%m-%Y") if @order.new_delivery_date %></strong> /// Car number: <strong><%= @order.car_number %></strong> </p>
    
  
    <p class="big-text flex-item"><strong>Additional Info: <%= simple_format(@order.info) %> </strong></p>
    <p class="big-text flex-item"><strong>Storage Info: <%= simple_format(@order.storage_info) %> </strong></p>



    <h3 class="align-center">Order Items:</h3>
    
    <table class=" table-auto border-2">
      <thead>
        <tr>
          <th></th>
          <th class="text-sm">Art. number</th>
          <th class="text-sm">Name</th>
          <th class="text-sm">Ordered stk</th>
          <th class="text-sm">Delivery stk</th>
          <th class="text-sm">Order/Delivery Weight</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_lists.sort_by { |order_list| order_list.part.description }.each_with_index do |order_list, index| %>
        <tr class="mb-4 ">
          <td><%= index + 1 %></td>
          <td><%= order_list.part.name %></td>
          <td><%= order_list.part.description %></td>
          <td class="text-center <%= 'gray-row' if order_list.delivery_quantity && order_list.quantity != order_list.delivery_quantity %>"><strong><%= order_list.quantity %></strong></td>
          <td class="text-center <%= 'gray-row' if order_list.delivery_quantity && order_list.quantity != order_list.delivery_quantity %>"><strong><%= order_list.delivery_quantity %></strong></td>
          <td class="text-center"><%= order_list.part.weight * order_list.quantity %> / <%= order_list.part.weight * order_list.delivery_quantity if order_list.delivery_quantity.present? %> kg</td>
        </tr>
        <% end %>
      </tbody>
    </table>

<div class="align-right">
<% unless total_weight(@order.order_lists) == total_order_delivery_weight(@order.order_lists) %>
  <p><strong>Order Weight: <%= total_weight(@order.order_lists) %> kg</strong></p>
<% end %>
  
  <% if @order.order_lists.any? { |list| list.delivery_quantity.present? } %>
  <p><strong>Delivery Weight: <%= total_order_delivery_weight(@order.order_lists) %> kg</strong></p>
<% end %>
 
</div>

<% if @order.order_storage_lists.any? %>
<h3 class="align-center">Parts added in Storage (Lagerman parts):</h3>
<table class="table-auto border-2">
  <thead>
    <tr>
    <th></th>
          <th class="text-sm">Art. number</th>
          <th class="text-sm">Name</th>
          <th class="text-sm">Stk.</th>
          <th class="text-sm">Comb. weight</th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_storage_lists.sort_by {|storage_list| storage_list.part.description }.each_with_index do |storage_list, index| %>
    <tr>
    <td><%= index + 1 %></td>
    <td> <%= storage_list.part.name %></td>
      
      <td><%= storage_list.description %></td>
      <td class="text-center"><strong><%= storage_list.quantity %></strong></td>
      <td class="text-center"><%= storage_list.weight %> kg</td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="align-right">
  <p><strong>Weight: <%= total_weight(@order.order_storage_lists) %> kg</strong></p>
</div>

<% end %>
<% unless total_weight(@order.order_storage_lists) +  total_weight(@order.order_lists) == total_weight(@order.order_storage_lists) + total_order_delivery_weight(@order.order_lists) %>
 <p><strong>Total Order Weight: <%= total_weight(@order.order_storage_lists) +  total_weight(@order.order_lists)%> kg</strong></p>
 <% end %>
<% if @order.order_lists.any? { |list| list.delivery_quantity.present? } %>
  <p><strong>Total Delivery Weight: <%= total_weight(@order.order_storage_lists) + total_order_delivery_weight(@order.order_lists) %> kg</strong></p>
<% end %>







<style>


.flex-container {
  display: flex;
  justify-content: space-between;
}

.flex-item {
  flex: 1; /* Pozwala elementom flex na rozwinięcie się i zajęcie dostępnego miejsca */
  padding: 0 10px; /* Opcjonalny padding dla lepszego wyglądu */
  box-sizing: border-box; /* Upewnia się, że padding i border są uwzględniane w całkowitej szerokości elementu */
}

.align-center {
  text-align: center;
}

.align-right {
  text-align: right;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th, td {
  border: 1px solid black;
  padding: 2px;
  text-align: left;
  padding-left: px;
}

th {
  background-color: #f2f2f2;
  text-align: center;
}

.big-text {
  font-size: 18px;
}

.text-sm {
  font-size: 12px;
}
.text-center {
  text-align: center;
}
.gray-row {
    background-color: #F0F8FF; /* Szary kolor */
}

    </style>

    </body>
</html>