config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users,
             ActiveAdmin::Devise.config.merge({ class_name: 'AdminUser',
                                                controllers: { sessions: 'custom_active_admin_sessions' } })

  ActiveAdmin.routes(self)
  devise_for :users, skip: :registrations
  get '/pages/index', to: 'pages#index'
  resources :parts
  resources :cart_items, only: [:create]
  resources :carts do
    resources :cart_items, only: %i[create update destroy]
    member do
      delete 'clear_cart'
    end
  end

  get 'orders/lager_order', to: 'orders#lager_order', as: 'lager_order'
  post 'orders/create_lager_order', to: 'orders#create_lager_order', as: 'create_lager_order'

  resources :orders, only: %i[new create show update edit] do
    member do
      get :complete
      get :set_to_pending
      get :set_to_missing_parts
      post :add_part
      delete :delete_part
      get :set_to_hide
      get :set_to_visible
    end
  end

  root 'pages#welcome'

  get '/get_full_address', to: 'orders#get_full_address'

  namespace :warehouse do
    resources :storages, only: %i[index show update] do
      member do
        # ... (inne akcje member)
        get :print
      end

      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get 'parts_on_site'
        get :hidden_orders
        get :visible_orders
        get :print
      end
    end
  end

  namespace :tracking do
    resources :orders do
      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get :your_orders
      end
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  attr_accessor :send_email

  attribute :storage_info, :text
  attribute :name, :string

  has_many :order_lists, dependent: :destroy
  has_many :parts, through: :order_lists
  belongs_to :user, -> { with_deleted }
  has_many :order_storage_lists, dependent: :destroy

  validates :building_site, presence: true
  validates :delivery_date, presence: true

  after_initialize :set_default_status, if: :new_record?

  accepts_nested_attributes_for :order_lists

  enum status: { pending: 'Pending', in_progress: 'In Progress', completed: 'Completed',
                 missing_parts: 'Missing Parts' }

  def set_default_status
    self.status ||= 'pending'
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[car_number building_site created_at delivery_date id info part_description part_number
       quantity updated_at weight user_id building_site_info status storage_info new_delivery_date hidden]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[order_lists parts order_storage_lists]
  end

  def delivery_date_cannot_be_in_the_past
    return unless delivery_date.present? && delivery_date < Date.today

    errors.add(:delivery_date, "can't be in the past")
  end

  def total_weight
    order_lists.sum { |list| list.part ? list.quantity * list.part.weight : 0 }
  end

  def set_to_hide
    self.hidden = true
    save
  end

  def set_to_visible
    self.hidden = false
    save
  end

  def recipients_emails(current_user)
    mailer_emails = { 'Scaffolder' => user.email }
    site = Site.find_by(name: building_site)
    mailer_emails['Site Ledermann'] = site.ledermann.email if site&.ledermann.present?
    mailer_emails['Your Email'] = current_user.email
    DeliveryEmail.pluck(:recipient_email).each_with_index do |email, index|
      mailer_emails["Email #{index + 1}"] = email
    end
    mailer_emails.uniq
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @cart = current_cart
    @products = @cart.cart_items.map do |item|
      { name: item.part.name, description: item.part.description, weight: item.part.weight, quantity: item.quantity }
    end
    @total_weight = calculate_total_weight
  end

  def create
    @order = Order.new(order_params.except(:order_lists_attributes))
    @order.user = current_user
    @order.status = 'pending'
    @cart = current_cart
    @products = @cart.cart_items.map do |item|
      { name: item.part.name, description: item.part.description, weight: item.part.weight, quantity: item.quantity }
    end
    @total_weight = calculate_total_weight

    if @order.save
      @cart.cart_items.each do |cart_item|
        @order.order_lists.create(
          part_id: cart_item.part_id,
          quantity: cart_item.quantity,
          description: cart_item.part.description,
          weight: cart_item.part.weight
        )
      end

      @order = Order.includes(:order_lists, :parts).find(@order.id)

      OrderMailer.order_confirmation(@order).deliver_now
      @cart.destroy
      session[:cart_id] = nil
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def lager_order
    @order = Order.new
    @cart = current_cart
    @products = @cart.cart_items.map do |item|
      { name: item.part.name, description: item.part.description, weight: item.part.weight, quantity: item.quantity }
    end
    @total_weight = calculate_total_weight
    @lager_site = Site.find_or_create_by(name: 'Lager - Storage')
    @order.building_site = @lager_site.name
    @order.delivery_date = Date.current
  end

  def create_lager_order
    @order = Order.new(order_params.except(:order_lists_attributes))
    @order.user = current_user
    @order.status = 'pending'
    @cart = current_cart
    @products = @cart.cart_items.map do |item|
      { name: item.part.name, description: item.part.description, weight: item.part.weight, quantity: item.quantity }
    end
    @total_weight = calculate_total_weight
    begin
      puts @products.inspect
      OrderMailer.lager_order_confirmation(@order, @products, @total_weight).deliver_now
      @cart.destroy
      session[:cart_id] = nil
      redirect_to root_path, notice: "Email sent to: #{current_user.email}"
    rescue StandardError => e
      Rails.logger.error("Error sending email: #{e.message}")
      redirect_to lager_order_path, alert: 'There was an error sending the email. Please try again.'
    end
  end

  def get_full_address
    site = Site.find_by(name: params[:site])

    if site
      render json: { full_address: site.address }
    else
      render json: { full_address: 'address not found' }, status: :not_found
    end
  end

  def complete
    @order = Order.find(params[:id])
    @order.completed!
    redirect_to request.referer || warehouse_storages_path, notice: 'Order set to Completed'
  end

  def set_to_missing_parts
    @order = Order.find(params[:id])

    @order.missing_parts!
    redirect_to request.referer || warehouse_storages_path, notice: 'Order set to Missing Parts'
  end

  def delivery_quantities_present?
    @order.order_lists.all? { |order_list| order_list.delivery_quantity.present? }
  end

  def in_progress?
    status == 'in_progress'
  end

  def set_to_pending
    @order = Order.find(params[:id])
    @order.pending!
    redirect_to request.referer || warehouse_storages_path, notice: 'Order set to Pending'
  end

  def set_to_hide
    order = Order.find(params[:id])
    order.set_to_hide
    redirect_to request.referer || warehouse_storages_path, notice: 'Order has been hidden.'
  end

  def set_to_visible
    order = Order.find(params[:id])
    order.set_to_visible
    redirect_to request.referer || warehouse_storages_path, notice: 'Order is visible.'
  end

  def add_part
    @order = Order.find(params[:id])

    @selected_system = System.find(params[:system_id]) if params[:system_id].present?

    @selected_category = Category.find(params[:category_id]) if params[:category_id].present?

    if params[:part_id].blank?
      redirect_to request.referrer || warehouse_storage_path(@order), alert: 'Please select a part.'
      return
    end

    @part = Part.find(params[:part_id])
    order_storage_list = OrderStorageList.find_or_initialize_by(order: @order, part: @part)

    if order_storage_list.persisted?
      order_storage_list.quantity += params[:quantity].to_i
    else
      order_storage_list.quantity = params[:quantity]
      order_storage_list.description = @part.description
      order_storage_list.weight = @part.weight
    end

    order_storage_list.save
    redirect_to request.referrer || warehouse_storage_path(@order), notice: 'Part added successfully.'
  end

  def delete_part
    @order = Order.find(params[:id])
    order_storage_list = OrderStorageList.find(params[:order_storage_list_id])

    if order_storage_list.order_id == @order.id
      order_storage_list.destroy
      redirect_to warehouse_storage_path(@order), notice: 'Successfully removed.'
    else
      redirect_to warehouse_storage_path(@order), alert: 'An error occurred while trying to remove the part.'
    end
  end

  private

  def order_params
    params.require(:order).permit(:building_site, :delivery_date, :info, :building_site_info, :new_delivery_date,
                                  :car_number, :status, :storage_info, :checkbox, :send_email, order_lists_attributes: %i[part_id quantity description delivery_quantity checkbox])
  end

  def calculate_total_weight
    @cart.cart_items.sum { |item| item.part.weight * item.quantity }
  end
end

app/controllers/tracking/orders_controller.rb
# frozen_string_literal: true

module Tracking
  class OrdersController < ApplicationController
    layout 'tracking'

    def index
      @all_orders_view = false
      start_date = params[:start_date].presence
      end_date = params[:end_date].presence
      site_id = params[:site].presence
      @start_date = params[:start_date]
      @end_date = params[:end_date]

      @orders = recent_orders.order(created_at: :desc)

      if start_date && end_date
        start_date = start_date.to_date.beginning_of_day
        end_date = end_date.to_date.end_of_day
        @orders = recent_orders.where(created_at: start_date..end_date)
        @all_orders_view = true
        flash[:notice] = 'Date selected'
      end
      if site_id
        site = Site.find(site_id)
        @orders = @orders.where(building_site: site.name)
        @site_name = site.name
      end

      @orders = @orders.limit(100) unless @all_orders_view
    end

    def search_orders
      site_id = params[:site].presence
      if site_id
        site = Site.find(site_id)
        @orders = Order.where(building_site: site.name)
        @site_name = site.name # Assigning the site name
      end
      render :index
    end

    def show
      @order = Order.find(params[:id])
    end

    def all_orders
      @orders = Order.order(created_at: :desc)
      @all_orders_view = true
      render :index
    end

    def your_orders
      @orders = Order.where(user: current_user).order(created_at: :desc)
      @your_orders_view = true
      render :index
    end

    def completed_orders
      @orders = Order.where(status: 'completed').order(created_at: :desc).limit(100)
      @status = 'completed'
      render :index
    end

    def pending_orders
      @orders = Order.where(status: 'pending').order(created_at: :desc).limit(100)
      @status = 'pending'
      render :index
    end

    def in_progress_orders
      @orders = Order.where(status: 'in_progress').order(created_at: :desc).limit(100)
      @status = 'in progress'
      render :index
    end

    def missing_parts_orders
      @orders = Order.where(status: 'missing_parts').order(created_at: :desc).limit(100)
      @status = 'missing parts'
      render :index
    end

    private

    def recent_orders
      six_months_ago = 6.months.ago
      Order.where('created_at > ?', six_months_ago)
    end

    def order_params
      params.require(:order).permit(:delivery_date, :new_delivery_date, :car_number, :storage_info,
                                    order_lists_attributes: %i[id delivery_quantity checkbox])
    end
  end
end

app/helpers/tracking/orders_helper.rb
# frozen_string_literal: true

module Tracking
  module OrdersHelper
  end
end

app/views/tracking/orders/index.html.erb
<button id="toggle-storage-menu" class="ml-4 btn btn-primary  rounded-lg p-1 flex inline bg-neutral-200 hover:bg-neutral-300" onclick="toggleMenu()"><%= image_tag "menu.png", class: "w-6 h-6 flex inline mr-1 " %>  Tracking Menu</button>
<div id="storage-menu" class="transition-all duration-500 max-h-0 overflow-hidden mt-2">
  <%= form_with url: tracking_orders_path, method: :get, local: true do |form| %>
    <%= form.label :site, "Search for:", class: "mr-1" %>
    <%= form.collection_select :site, Site.order(:name), :id, :name, { prompt: "Choose a site" }, { class: "w-44 rounded-lg" } %>
    <div class="mb-2">
      <%= form.label :start_date, "From:" %>
      <%= form.date_field :start_date, class: "w-20 border-1 rounded-lg" %>
      <%= form.label :end_date, "To:" %>
      <%= form.date_field :end_date, class: "w-20 border-1 rounded-lg" %>
      <%= image_submit_tag 'search.png', class: 'w-8 h-8', alt: 'Search' %>
    <% end %>
  </div>
  <div class="flex justify-between ">
    <div class="flex inline ">
      Select only:
      <%= button_to pending_orders_tracking_orders_path, method: :get, class: 'your-button-classes m-1' do %>
        <%= image_tag('hourglass.png', size: '20x20', alt: 'Show Completed Orders') %>
      <% end %>
      <%= button_to in_progress_orders_tracking_orders_path, method: :get, class: 'your-button-classes m-1' do %>
        <%= image_tag('list.png', size: '20x20', alt: 'Show Completed Orders') %>
      <% end %>
      <%= button_to missing_parts_orders_tracking_orders_path, method: :get, class: 'your-button-classes m-1' do %>
        <%= image_tag('missing_parts.png', size: '20x20', alt: 'Show Missing Orders') %>
      <% end %>
      <%= button_to completed_orders_tracking_orders_path, method: :get, class: 'your-button-classes m-1' do %>
        <%= image_tag('ok.png', size: '20x20', alt: 'Show Completed Orders') %>
      <% end %>
    </div>
    <div class= "flex inline justify-end">
      <div data-controller="lightbox">
        <%= link_to asset_path('instruction_tracking.png'), data: { lightbox: 'instruction', title: 'Instruction' } do %>
          <div class= "flex inline">
            <%= image_tag('instruction_img.png', size: '20x20', class: 'inline mr-1') %>
            <%= button_to " Instruction", class: "your-button-classes ml-2" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="border-b-2">
    <p class=""><%= button_to 'Show All Orders', all_orders_tracking_orders_path, method: :get, class: 'your-button-classes' %></p>
    <p class=""><%= button_to 'Show Your Orders', your_orders_tracking_orders_path, method: :get, class: 'your-button-classes' %></p>
  </div>
</div>
<% if @start_date && @end_date %>
  <p class="flex justify-center text-slate-400 mt-2">Orders from <%= @start_date %> to <%= @end_date %></p>
<% end %>
<% if @site_name %>
  <p class="flex justify-center text-slate-400 mt-2">Orders for site: <%= @site_name %></p>
<% end %>
<% if @orders.present?  %>
  <% if @all_orders_view == true %>
    <h1 class="text-center m-4">All orders</h1>
  <% else %>
    <h1 class="text-center m-4">Last 100 orders:</h1>
  <% end %>
  <div class="flex justify-center items-center ">
    <table class="table-fixed m-1">
      <thead>
        <tr>
          <th>Order no:</th>
          <th>Site</th>
          <th>Created</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <tr class="transition duration-300 hover:bg-slate-300 border ">
            <td class="m-20"> <%= link_to tracking_order_path(order), class: "ml-2" do %>
                <%= image_tag('go_to.png', size: '30x30', class: 'inline') %>
                <%= order.id %>
              <% end %></td>
            <td class="m-2 text-sm "><%= order.building_site %></td>
            <td class="m-2 text-sm text-center"> <%= order.created_at.strftime("%Y-%m-%d") %>
              <br/>
              <%= order.created_at.strftime("%H:%M")  %></td>
            <td class="m-2 border-r-2">
              <% if order.status == "completed" %>
                <p class="text-green-400"><%= image_tag('ok.png', size: '40x40', alt: "Completed") %></p>
              <% elsif order.status == "pending" %>
                <p class="text-red-400"><%= image_tag('hourglass.png', size: '40x40', alt: "Pending") %></p>
              <% elsif order.status == "missing_parts" %>
                <p class="text-text-amber-600"><%= image_tag('missing_parts.png', size: '40x40', alt: "Missing parts") %></p>
              <% else %>
                <p class="text-blue-400"><%= image_tag('list.png', size: '40x40', alt: "In Progress") %></p>
              <% end %>
            </td>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="flex justify-center item-center mt-10" >No orders <%= @status %></p>
<%end%>
</div>
<script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/tw-elements.umd.min.js"></script>
<script>
  function toggleMenu() {
    var menu = document.getElementById('storage-menu');
    if (menu.style.maxHeight === "" || menu.style.maxHeight === "0px") {
      menu.style.maxHeight = menu.scrollHeight + "px";
      localStorage.setItem('storageMenuState', 'open');
    } else {
      menu.style.maxHeight = "0px";
      localStorage.setItem('storageMenuState', 'closed');
    }
  }

  document.addEventListener('DOMContentLoaded', (event) => {
    var menu = document.getElementById('storage-menu');
    var state = localStorage.getItem('storageMenuState');
    if (state === 'open') {
      menu.style.maxHeight = menu.scrollHeight + "px";
    }
  });
</script>

app/views/tracking/orders/show.html.erb
<% if @order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
    <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="mb-1  ml-2 mt-2 text-left">
  <button class="inline-flex items-center  px-1 py-1  bg-transparent hover:bg-slate-300 text-black text-sm font-medium rounded-md border border-black hover:scale-110 transition duration-200" onclick="history.back()">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
    </svg>
    back
  </button>
</div>
<p class=" text-center ">Order: <%= @order.id %></p>
<p class=" text-center text-sm">Created at: <%= @order.created_at.strftime("%d-%m-%Y") %></p>
<p class="text-lg text-center ">Status: <%= @order.status.gsub('_', ' ').titleize %></p>
<p class="flex justify-center mb-4">
  <% if @order.pending? %>
    <%= image_tag('hourglass.png', size: '40x40', alt: "Pending") %>
  <% elsif @order.in_progress? %>
    <%= image_tag('list.png', size: '40x40', alt: "In Progress") %>
  <% elsif @order.missing_parts? %>
    <%= image_tag('missing_parts.png', size: '40x40', alt: "Missing parts") %>
  <% else %>
    <%= image_tag('ok.png', size: '40x40', alt: "Completed") %>
  <% end %>
</p>
<p class="text-sm">Scaffolder: <%= @order.user.name %> <%= @order.user.email %></p>
<p class="text-sm">Building Site: <strong><%= @order.building_site %></strong></p>
<% if @order.building_site_info.present? %>
  <p class="text-sm">Site info: <%= @order.building_site_info %></p>
<% end %>
<div class= "flex inline justify-end mr-2">
  <div data-controller="lightbox">
    <%= link_to asset_path('instruction_parts.png'), data: { lightbox: 'instruction', title: 'Instruction' } do %>
      <div class= "flex inline">
        <%= image_tag('instruction_img.png', size: '20x20', class: 'inline mr-1') %>
        <%= button_to " Instruction", class: "your-button-classes ml-2" %>
      </div>
    <% end %>
  </div>
</div>
<% if @order.order_storage_lists.any? %>
  <h2 class="mt-10 text-purple-900 mb-4">Additional/more parts from Lagermann:</h2>
  <% total_storage_weight = 0 %>
  <%= form_with(model: @order, url: warehouse_storage_path(@order), method: :patch) do |form| %>
    <% @order.order_storage_lists.includes(:part).sort_by { |osl| osl.description.downcase }.each_with_index do |order_storage_list, index| %>
      <%= form.fields_for :order_storage_lists, order_storage_list do |order_storage_list_form| %>
        <div class=" ml-1 border-b-2 flex justify-between">
          <p class="text-sm  mb-4 inline">
            <%= index + 1 %>.<%= order_storage_list.description %>--
          </p>
          <div class="text-right">
            <span class="text-sm text-indigo-800 "><%= order_storage_list.quantity %> stk</span>
          </div>
        </div>
        <% total_storage_weight += order_storage_list.quantity * order_storage_list.weight %>
      <% end %>
    <% end %>
  <% end %>
<% end %>
<h2 class="mt-4 ml-1 mr-1">Ordered Parts:</h2>
<% total_weight = 0 %>
<%= form_with(model: @order, url: warehouse_storage_path(@order), method: :patch) do |form| %>
  <% @order.order_lists.includes(:part).sort_by { |ol| ol.description.downcase }.each_with_index do |order_list, index| %>
    <%= form.fields_for :order_lists, order_list do |order_list_form| %>
      <div class="m-1 border-b-2 flex">
        <div class="flex-grow">
          <% if order_list.delivery_quantity.present? %>
            <% if order_list.delivery_quantity > order_list.quantity %>
              <% highlight_class = 'text-amber-500' %>
            <% elsif order_list.delivery_quantity < order_list.quantity %>
              <% highlight_class = 'text-red-800' %>
            <% else %>
              <% highlight_class = 'text-green-800' %>
            <% end %>
          <% else %>
            <% highlight_class = 'text-black' %>
          <% end %>
          <p class="text-sm mb-2 <%= highlight_class %>"><%= index + 1 %>. <%= order_list.description %></p>
        </div>
        <div class="flex flex-grow justify-end">
          <p class=" text-indigo-800"><strong><%= order_list.quantity %></strong>/</p>
          <p class="<%= highlight_class %>   ">
            <% if order_list.delivery_quantity.present? %>
              <%= order_list.delivery_quantity %>
            <% else %>
              ???
            <% end %>
            stk</p>
        </div>
        <% total_weight += order_list.quantity * order_list.weight %>
      </div>
    <% end %>
  <% end %>
  <% if @order.info.present? %>
    <p class="mt-10 m-1 text-sm"><strong>Additional Info/Parts:</strong> <%= simple_format(@order.info,  class: "text-sm m-1" )%></p>
  <% end %>
  <% if @order.storage_info.present? %>
    <div class="mt-4 m-1">
      <p><strong><%= form.label :storage_info, "Storage Parts/Delivery Info:", class: " mt-2 " %></strong></p>
      <p><%= simple_format(@order.storage_info) %></p>
    </div>
  <% end %>
  <% if @order.new_delivery_date.present? %>
    <div class="mt-4 justify-center text-center">
      <p class="text-sm mt-4 m-1">Delivery Date wanted: <%= @order.delivery_date.strftime("%d-%m-%Y") %></p>
      <p class="text-lg"> <strong> New delivery date: <%= @order.new_delivery_date.strftime("%d-%m-%Y") %> </strong></p>
    </div>
  <% else %>
    <div class="mt-4 justify-center text-center">
      <p class="text-lg mt-4">Delivery Date: <%= @order.delivery_date.strftime("%d-%m-%Y") %></p>
    </div>
  <% end %>
  <% if @order.car_number.present? %>
    <div class="flex justify-center mt-4">
      Car number: <%= @order.car_number%>
    </div>
  <% end %>
<% end %>
<p class="text-center m-4"><strong>Order Weight:</strong> <%= total_weight %>kg</p>
<% if @order.status == "completed" || @order.status == "missing_parts" %>
  <p class="text-center m-4"><strong>Delivery Weight</strong>: <%= total_delivery_weight(@order.order_lists, @order.order_storage_lists) %>kg</p>
<% else %>
  <p class="text-center m-4"><strong>Delivery Weight</strong>: Not completed</p>
<% end %>
<script src="https://cdn.jsdelivr.net/npm/tw-elements/dist/js/tw-elements.umd.min.js"></script>