config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users,
             ActiveAdmin::Devise.config.merge({ class_name: 'AdminUser',
                                                controllers: { sessions: 'custom_active_admin_sessions' } })

  ActiveAdmin.routes(self)
  devise_for :users, skip: :registrations
  get '/pages/index', to: 'pages#index'
  resources :parts
  resources :cart_items, only: [:create]
  resources :carts do
    resources :cart_items, only: %i[create update destroy]
    member do
      delete 'clear_cart'
    end
  end

  get 'orders/lager_order', to: 'orders#lager_order', as: 'lager_order'
  post 'orders/create_lager_order', to: 'orders#create_lager_order', as: 'create_lager_order'

  resources :orders, only: %i[new create show update edit] do
    member do
      get :complete
      get :set_to_pending
      get :set_to_missing_parts
      post :add_part
      delete :delete_part
      get :set_to_hide
      get :set_to_visible
    end
  end

  root 'pages#welcome'

  get '/get_full_address', to: 'orders#get_full_address'

  namespace :warehouse do
    resources :storages, only: %i[index show update] do
      member do
        # ... (inne akcje member)
        get :print
      end

      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get 'parts_on_site'
        get :hidden_orders
        get :visible_orders
        get :print
      end
    end
  end

  namespace :tracking do
    resources :orders do
      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get :your_orders
      end
    end
  end
end

app/views/shared/_cart.html.erb
<% unless current_page?(new_order_path) %>
  <% if @view_mode == 'desktop' %>
    <strong>Items in cart:</strong>
    <% unless @cart && @cart.cart_items.any? %>
      <p>Cart is empty</p>
    <% end %>
  <% end %>
  <% if @cart && @cart.cart_items.any? %>
    <div class="flex justify-center text-sm w-120">
      <div>
        <% if @view_mode != 'desktop' %>
          <strong>Items in cart:</strong>
        <% end %>
        <div class="flex justify-end">
          <% if @cart && @cart.cart_items.any? %>
            <div data-controller="dialog">
              <dialog data-dialog-target="dialog" class="rounded shadow-lg p-4">
                <p class="text-lg">Clear all items from the cart?</p>
                <div class="mt-4 flex justify-end gap-4">
                  <%= button_to clear_cart_cart_path(@cart), method: :delete, class: "bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-200" do %>
                    Yes, Clear All
                  <% end %>
                  <button type="button" data-action="dialog#close" class="bg-gray-300 px-4 py-2 rounded hover:bg-gray-400 transition duration-200">Cancel</button>
                </div>
              </dialog>
              <button type="button" data-action="dialog#open" class=" inline-flex items-center px-4 py-2 bg-transparent hover:bg-red-500 text-red-500 hover:text-white text-sm font-medium rounded-md border border-red-500">
                <strong>Clear all cart</strong>
              </button>
            </div>
          <% end %>
        </div>
        <% sorted_cart_items = cart.cart_items.sort_by { |item| item.created_at }.reverse %>
        <% sorted_cart_items.each_with_index do |item, index| %>
          <div class="flex items-center justify-between border-b-2 mt-4 px-2 <%= index.even? ? 'bg-gray-200 rounded' : '' %> <%= @view_mode == 'desktop' ? 'text-lg' : '' %>">
            <!-- Delete Button -->
            <div data-controller="dialog">
              <dialog data-dialog-target="dialog" class="rounded shadow-lg p-4">
                <p>Delete <%=item.part.description %> from the cart?</p>
                <div class="mt-4 flex justify-end gap-4">
                  <%= button_to cart_cart_item_path(@cart, item), method: :delete, class: "bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600 transition duration-200" do %>
                    Yes, Delete
                  <% end %>
                  <button type="button" data-action="dialog#close" class="bg-gray-300 px-4 py-2 rounded hover:bg-gray-400 transition duration-200">Cancel</button>
                </div>
              </dialog>
              <button type="button" data-action="dialog#open" class="mr-2 px-2 text-red-500 border border-red-500 rounded hover:bg-red-500 hover:text-white transition duration-200">
                X
              </button>
            </div>
            <!-- Item Details -->
            <p class="flex-grow">
              <strong class="text-blue-800 underline"><%= item.quantity %></strong>-stk/<strong><%= item.part.name %></strong>/ <%= item.part.description %>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash_notification.html.erb
<div class="fixed top-0 left-1/2 mt-4">
  <% flash.each do |key, value| %>
    <div
      data-controller="notification"
      data-notification-delay-value="2000"
      class=" transform -translate-x-1/2 transition transform duration-1000 bg-white border-b-4 p-4 shadow-md z-50 w-[300px] w-full"
      data-transition-enter-from="opacity-0 -translate-y-6"
      data-transition-enter-to="opacity-100 translate-y-0"
      data-transition-leave-from="opacity-100 translate-y-0"
      data-transition-leave-to="opacity-0 -translate-y-6"
    >
      <p class="<%= key == 'notice' ? 'text-green-700' : 'text-red-700' %> font-semibold text-lg text-center">
        <%= value %>
      </p>
      <button data-action="notification#hide" class="text-gray-500 hover:text-gray-800 font-semibold text-lg ml-4">X</button>
    </div>
  <% end %>
</div>

app/views/shared/_log_in.html.erb
<div class="flex justify-center mt-2 text-sm mb-15">
  <% if user_signed_in? %>
    <div class="flex justify-end container w-80">
      <div class="mr-2">
        <p class="">Logged as: <%= current_user.email %> </p>
        <p class="text-center">Status: <%= current_user.status.capitalize %> </p>
        <p class="text-center underline"> <%= link_to 'Admin Panel', '/admin', class: 'hover:underline' %> </p>
      </div>
      <div class="mt-4 hover:scale-110 transition duration-200">
        <%= button_to destroy_user_session_path, method: :delete, class: "logout-button" do %>
          <%= image_tag "exit_2.png", alt: "Log out", size: "50x50" %>
          <span class="text-sm">Log Out</span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_main_footer.html.erb
<div class="flex justify-center mt-5 text-center  ">
  <% if current_user && current_user.status.in?(["lagermann", "admin"]) %>
    <%= link_to warehouse_storages_path do %>
      <div class="flex flex-col items-center mr-6 hover:scale-110 transition duration-200">
        <%= image_tag("storage.png", alt: "Warehouse storage", width: 30, height: 30) %>
        <span>Storage</span>
      </div>
    <% end %>
  <% end %>
  <%= link_to tracking_orders_path do %>
    <div class="flex flex-col items-center ml-6 hover:scale-110 transition duration-200">
      <%= image_tag("cart_black.png", alt: "Order status", width: 55, height: 55) %>
      <span>Order status</span>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div>
  <div class="flex justify-between w-80">
    <div class="hover:scale-110 transition duration-200">
      <%= link_to root_path, class: "items-center" do %>
        <p class="">Back to Systems:</p>
        <div class="flex inline ml-3">
          <%= image_tag("peri_small.webp", alt: "Opis", size: "20x20") %>
          <%= image_tag("haki_small.webp", alt: "Opis", size: "20x20") %>
          <%= image_tag("alfix_small.webp", alt: "Opis", size: "20x20") %>
          <%= image_tag("rullestias_small.webp", alt: "Opis", size: "20x20") %>
          <%= image_tag("combisafe_small.webp", alt: "Opis", size: "20x20") %>
        </div>
      <% end %>
    </div>
    <% unless controller_name == "carts" || controller_name == "orders" %>
      <div class="hover:scale-110 transition duration-200">
        <%= link_to cart_path(current_cart.id), class: "items-center" do %>
          <p class="">Go to Order Cart</p>
          <p class="ml-12"><%= image_tag("cart_2.png", alt: "Opis", size: "30x30") %></p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_storage_footer.html.erb
<div class="flex justify-center mt-5 text-center  mb-4">
  <%= link_to root_path do %>
    <div class="flex flex-col items-center mr-6 hover:scale-110 transition duration-200">
      <%= image_tag("peri.jpg", alt: "Warehouse storage", width: 30, height: 30) %>
      <span>Order Site</span>
    </div>
  <% end %>
  <%= link_to tracking_orders_path do %>
    <div class="flex flex-col items-center ml-6 hover:scale-110 transition duration-200">
      <%= image_tag("cart_black.png", alt: "Order status", width: 55, height: 55) %>
      <span>Order status</span>
    </div>
  <% end %>
</div>

app/views/shared/_storage_navbar.html.erb
<div class="bg-white">
  <div class="">
    <%= link_to warehouse_storages_path do %>
      <div class="flex flex-col items-center  mt-2">
        <span class="text-lg text-center transition duration-300 hover:underline">STORAGE PANEL MAIN SITE</span>
      </div>
    <% end %>
  </div>

app/views/shared/_tracking_footer.html.erb
<div class="flex justify-center mt-5 text-center  mb-4">
  <%= link_to root_path do %>
    <div class="flex flex-col items-center mr-6 hover:scale-110 transition duration-200">
      <%= image_tag("peri.jpg", alt: "Warehouse storage", width: 30, height: 30) %>
      <span>Order Site</span>
    </div>
  <% end %>
  <% if current_user.status.in?(["lagermann", "admin"]) %>
    <%= link_to warehouse_storages_path do %>
      <div class="flex flex-col items-center ml-6 hover:scale-110 transition duration-200">
        <%= image_tag("storage.png", alt: "Storage", width: 30, height: 30) %>
        <span>Storage</span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_tracking_navbar.html.erb
<div class="bg-white">
  <div class="">
    <%= link_to tracking_orders_path do %>
      <div class="flex flex-col items-center  mt-2">
        <span class="text-lg text-center transition duration-300 hover:underline">TRACKING PANEL MAIN SITE</span>
      </div>
    <% end %>
  </div>