config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :admin_users,
             ActiveAdmin::Devise.config.merge({ class_name: 'AdminUser',
                                                controllers: { sessions: 'custom_active_admin_sessions' } })

  ActiveAdmin.routes(self)
  devise_for :users, skip: :registrations
  get '/pages/index', to: 'pages#index'
  resources :parts
  resources :cart_items, only: [:create]
  resources :carts do
    resources :cart_items, only: %i[create update destroy]
    member do
      delete 'clear_cart'
    end
  end

  get 'orders/lager_order', to: 'orders#lager_order', as: 'lager_order'
  post 'orders/create_lager_order', to: 'orders#create_lager_order', as: 'create_lager_order'

  resources :orders, only: %i[new create show update edit] do
    member do
      get :complete
      get :set_to_pending
      get :set_to_missing_parts
      post :add_part
      delete :delete_part
      get :set_to_hide
      get :set_to_visible
    end
  end

  root 'pages#welcome'

  get '/get_full_address', to: 'orders#get_full_address'

  namespace :warehouse do
    resources :storages, only: %i[index show update] do
      member do
        # ... (inne akcje member)
        get :print
      end

      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get 'parts_on_site'
        get :hidden_orders
        get :visible_orders
        get :print
      end
    end
  end

  namespace :tracking do
    resources :orders do
      collection do
        get :completed_orders
        get :pending_orders
        get :in_progress_orders
        get :all_orders
        get :search_orders
        get :missing_parts_orders
        get :your_orders
      end
    end
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :parts, through: :cart_items
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
    @cart_items = @cart.cart_items.includes(:part)
    @total_weight = calculate_total_weight
  end

  def clear_cart
    @cart = Cart.find(params[:id])
    @cart.cart_items.destroy_all
    redirect_back(fallback_location: root_path, notice: 'Cart cleared!')
  end

  private

  def calculate_total_weight
    total_weight = 0
    @cart_items.each do |cart_item|
      total_weight += cart_item.part.weight * cart_item.quantity
    end
    total_weight
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/show.html.erb
<div class="container flex justify-between">
  <div class="mb-3  ml-2 mt-2 text-left">
    <button class="inline-flex items-center  px-4 py-2 bg-transparent hover:bg-slate-300 text-black text-sm font-medium rounded-md border border-black hover:scale-110 transition duration-200" onclick="history.back()">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6" />
      </svg>
      back
    </button>
  </div>
  <div class="mb-3 mr-2 mt-2 bg-red-100 hover:scale-110 transition duration-200" data-controller="dialog">
    <dialog data-dialog-target="dialog" class="rounded shadow-lg p-4">
      <p>Are you sure you want to clear the cart?</p>
      <div class="mt-4 flex justify-end gap-4">
        <%= button_to clear_cart_cart_path(@cart), method: :delete, class: "bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-full shadow" do %>
          Yes, Clear All
        <% end %>
        <button type="button" data-action="dialog#close" class="bg-gray-300 px-4 py-2 rounded-full shadow hover:bg-gray-400 transition duration-200">Cancel</button>
      </div>
    </dialog>
    <button type="button" data-action="dialog#open" class="inline-flex items-center px-4 py-2 bg-transparent hover:bg-slate-300 text-black text-sm font-medium rounded-md border border-black">
      <%= image_tag "trash.png", size: "15x15", alt: "Delete", class: "mr-2" %>
      Clear cart
    </button>
  </div>
</div>
<% if @cart.cart_items.empty? %>
  <h1>Your Order Cart is Empty</h1>
<% else %>
  <h1>Your Order Cart:</h1>
<% end %>
<div class="mt-6">
  <% sorted_cart_items = @cart.cart_items.sort_by { |item| item.created_at } %>
  <% sorted_cart_items.each do |item| %>
    <p class=""><%= item.part.description %></p>
    <% if item.part.multipack > 1 %>
      <p class=""><strong>Multipack: <%= item.part.multipack%></strong></p>
    <% end %>
    <% if @cart.present? %>
      <p class="ml-3 text-green-500">Currently in cart: <strong><%= @cart.cart_items.find_by(part_id: item.part_id).quantity %></strong></p>
    <% end %>
    <div class="border-b-2 mb-4 flex justify-between">
      <div>
        <%= form_with(model: item, url: cart_cart_item_path(@cart, item), method: :patch) do |form| %>
          <%= form.number_field :quantity, value: item.quantity, class: " w-20", id: "quantity-field", min: 1 %>
          <p><%=  image_submit_tag("edit.png", alt: "Update Quantity", class: "mt-1 ml-4 h-10 w-10 hover:scale-110 transition duration-200  hover:bg-green-200 rounded") %></p>
        <% end %>
      </div>
      <div>
        <% if item.part.image.attached? %>
          <%= image_tag(
            item.part.image.variant(
              resize_to_limit: [80, 80], # Ograniczenie rozmiaru
              saver: { quality: 90 },   # Ustawienie jakości na 90%
              format: :webp             # Konwersja na format WEBP
            ),
            alt: item.part.name
          ) %>
        <% else %>
          <%= image_tag "scaffold_img_small.webp", size: "80x80", alt: "img" %>
        <% end %>
      </div>
      <div data-controller="dialog">
        <dialog data-dialog-target="dialog" class="rounded shadow-lg p-4">
          <p>Delete <%= item.part.description %> from the cart?</p>
          <div class="mt-4 flex justify-end gap-4">
            <%= button_to cart_cart_item_path(@cart, item), method: :delete, class: "bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-full shadow" do %>
              Yes, Delete
            <% end %>
            <button type="button" data-action="dialog#close" class="bg-gray-300 px-4 py-2 rounded-full shadow hover:bg-gray-400 transition duration-200">Cancel</button>
          </div>
        </dialog>
        <button type="button" data-action="dialog#open" class=" hover:bg-red-600 text-white px-3 py-1 rounded-full shadow hover:scale-110 transition duration-200">
          <%= image_tag "trash.png", size: "30x30", alt: "Delete", class: "inline-block" %>
        </button>
      </div>
    </div>
  <% end %>
</div>
<div class="m-3 flex">
  <%= image_tag "weight.png", size: "40x20", alt:"weight"%>
  <p class="text-center m-2">Total Weight: <%= @total_weight %> kg</p>
</div>
<div class="m-3">
  <%= button_to new_order_path(cart_id: @cart.id), method: :get, 
    class: "inline-flex items-center px-4 py-2 bg-gray-500 hover:bg-gray-700 text-white font-semibold rounded-md",
    disabled: @cart.cart_items.empty? do %>
    <%= image_tag "cart.png", size: "40x20", alt: "Order" %>
    <span class="ml-2 ">GO to Scaffolder Order</span>
  <% end %>
</div>
<div class="container text-right">
  <div class="flex justify-end items-center mt-40 mb-3">
    <div class="tooltip-container mr-2">
      <span class="question-mark">?</span>
      <div class="tooltip-text">Order will not be saved. Only email is sent to You.</div>
    </div>
    <div class="mr-2">
      <%= button_to lager_order_path(cart_id: @cart.id), method: :get, 
        class: "inline-flex items-center px-4 py-2 bg-gray-300 hover:bg-gray-500 text-white font-semibold rounded-md",
        disabled: @cart.cart_items.empty? do %>
        <%= image_tag "storage.png", size: "20x20", alt: "Lager Order" %>
        <span class="ml-2 ">Lager Order</span>
      <% end %>
    </div>
  </div>
</div>
<script>
  document.querySelector('.question-mark').addEventListener('click', function(event) {
    const tooltip = this.nextElementSibling;
    if (tooltip.style.visibility === 'visible') {
      tooltip.style.visibility = 'hidden';
      tooltip.style.opacity = '0';
    } else {
      tooltip.style.visibility = 'visible';
      tooltip.style.opacity = '1';
      event.stopPropagation(); // Zapobiega wywołaniu zdarzenia na document
    }
  });

  document.addEventListener('click', function() {
    const tooltip = document.querySelector('.tooltip-text');
    if (tooltip.style.visibility === 'visible') {
      tooltip.style.visibility = 'hidden';
      tooltip.style.opacity = '0';
    }
  });
</script>